name: Tests

on:
  push:
  workflow_dispatch:

jobs:
  test-upload-file:
    runs-on: ubuntu-latest
    name: Test upload
    steps:
      - id: upload
        uses: biglocalnews/upload-files@main
        with:
          api-key: ${{ secrets.BLN_API_KEY }}
          project-id: ${{ secrets.BLN_PROJECT_ID }}
          path: ./tests/test.csv
